variables:
    APP: innovplay_site
    ENVIRONMENT: prod
    RUNNER: vps
    IMAGE_TAG: "$APP:latest"
    CONTAINER_NAME: "$APP"
    HOST_PORT: 8000
    CONTAINER_PORT: 80

workflow:
    rules:
        - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME != 'dev'"
          variables:
              ENVIRONMENT: local
              RUNNER: local
              IMAGE_TAG: "$APP:local"
              CONTAINER_NAME: "$APP-local"
              VITE_API_BASE_URL: /api
              API_CONTAINER: innovplay_api-local
        - if: "$CI_COMMIT_BRANCH == 'dev'"
          variables:
              ENVIRONMENT: dev
              IMAGE_TAG: "$APP:dev"
              CONTAINER_NAME: "$APP-dev"
              HOST_PORT: 8001
        - if: "$CI_COMMIT_BRANCH == 'main'"
        - when: never

stages:
    - validate_pipeline
    - prebuild
    - build
    - deploy
    - clean

.set_runner_tag:
    tags:
        - $RUNNER

.set_none_git_strategy:
    variables:
        GIT_STRATEGY: none

.clean_job:
    script:
        - |
            CONTAINER_IDS=$(docker container ls -a -f ancestor="$IMAGE_TAG" -q)

            if [ -z "$CONTAINER_IDS" ]; then
                echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Container do app não existe."
            else
                for ID in $CONTAINER_IDS; do
                    IS_RUNNING=$(docker inspect -f "{{.State.Running}}" "$ID")

                    if [ "$IS_RUNNING" = "true" ]; then
                        docker container stop "$ID"

                        echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Container do app com id '$ID' foi parado."
                    else
                        echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Container do app com id '$ID' já está parado."
                    fi

                    docker container rm "$ID"

                    echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Container do app com id '$ID' foi removido."
                done
            fi
        - |
            IMAGE_ID=$(docker image ls -f reference="$IMAGE_TAG" -q)

            if [ -z "$IMAGE_ID" ]; then
                echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Imagem '$IMAGE_TAG' não existe."
            else
                docker image rm "$IMAGE_ID"

                echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Imagem '$IMAGE_TAG' com id '$IMAGE_ID' foi removida."
            fi

invalid_merge_request:
    stage: validate_pipeline
    extends:
        - .set_runner_tag
        - .set_none_git_strategy
    rules:
        - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'"
    script:
        - |
            echo "$(date '+[%Y-%m-%d %H:%M:%S]') - MR para 'main' só é permitido a partir da branch 'dev'."
            exit 1

image_clean:
    stage: prebuild
    extends:
        - .set_runner_tag
        - .set_none_git_strategy
        - .clean_job
    before_script:
        - |
            command -v docker >/dev/null || { echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Docker não disponível"; exit 1; }

image_build:
    stage: build
    extends:
        - .set_runner_tag
    environment:
        name: $ENVIRONMENT
    script:
        - |
            set -e

            echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" > .env

            envsubst '$API_CONTAINER' < nginx.conf.template > nginx.conf

            docker build --no-cache -t "$IMAGE_TAG" .

            IMAGE_ID=$(docker image ls -f reference="$IMAGE_TAG" -q)

            if [ -z "$IMAGE_ID" ]; then
                echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Imagem '$IMAGE_TAG' não foi encontrada após o build."
                exit 1
            else
                echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Imagem '$IMAGE_TAG' criada com id '$IMAGE_ID'."
            fi

network_create:
    stage: predeploy
    extends:
        - .set_runner_tag
        - .set_none_git_strategy
    script:
        - |
            set -e

            NETWORK=$(docker network ls -f name="^${ENVIRONMENT}$" -q)

            if [ -z "$NETWORK" ]; then
                docker network create "$ENVIRONMENT"

                NETWORK=$(docker network ls -f name="^${ENVIRONMENT}$" -q)

                if [ -z "$NETWORK" ]; then
                    echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Falha ao criar a network '$ENVIRONMENT'."
                    exit 1
                else
                    echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Network '$ENVIRONMENT' criada com sucesso."
                fi
            else
                echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Network '$ENVIRONMENT' já existe."
            fi

container_run:
    stage: deploy
    extends:
        - .set_runner_tag
        - .set_none_git_strategy
    environment:
        name: $ENVIRONMENT
        on_stop: environment_clean
    script:
        - |
            set -e

            docker container run --network "$ENVIRONMENT" -p "$HOST_PORT:$CONTAINER_PORT" --name "$CONTAINER_NAME" -d "$IMAGE_TAG"

            CONTAINER_ID=$(docker container ls -a -f ancestor="$IMAGE_TAG" -q)

            if [ -z "$CONTAINER_ID" ]; then
                echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Falha ao criar o container '$CONTAINER_NAME'."
                exit 1
            else
                sleep 30

                IS_RUNNING=$(docker inspect -f "{{.State.Running}}" "$CONTAINER_ID")

                if [ "$IS_RUNNING" = "true" ]; then
                    echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Container '$CONTAINER_NAME' criado com id '$CONTAINER_ID'."
                else
                    echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Falha ao criar o container '$CONTAINER_NAME'."
                    exit 1
                fi
            fi

environment_clean:
    stage: clean
    extends:
        - .set_none_git_strategy
        - .clean_job
    environment:
        name: $ENVIRONMENT
        action: stop
    rules:
        - if: "$ENVIRONMENT == 'local'"
          when: manual
    allow_failure: true
    after_script:
        - |
            NETWORK=$(docker network ls -f name="^${ENVIRONMENT}$" -q)

            if [ -z "$NETWORK" ]; then
                echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Network '$ENVIRONMENT' não existe."
            else
                docker network rm "$NETWORK"

                echo "$(date '+[%Y-%m-%d %H:%M:%S]') - Network '$ENVIRONMENT' foi removida."
            fi
