services:
  app:
    image: afirmeplay/afirmeplay-frontend:${VERSION}
    container_name: afirmeplay_front_prod
    environment:
      - VITE_API_BASE_URL=$VITE_API_BASE_URL
      - SUBDOMAIN_MODE=$SUBDOMAIN_MODE
      - API_CONTAINER=$API_CONTAINER
    ports:
      - "8081:80"
    networks:
      - prod
    restart: unless-stopped


networks:
  prod:
    driver: bridge