services:
  app:
    image: afirmeplay/afirmeplay-frontend:${VERSION}
    container_name: afirmeplay_front_dev
    environment:
      - VITE_API_BASE_URL=$VITE_API_BASE_URL
      - SUBDOMAIN_MODE=$SUBDOMAIN_MODE
      - API_CONTAINER=$API_CONTAINER
    ports:
      - "8080:80"
    networks:
      - dev
    restart: unless-stopped


networks:
  dev:
    driver: bridge